### ISSUE TITLE
Create default LoopBack API docs for AngularJS SDK

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback-sdk-angular#87]
We have API docs for our iOS and Android SDKs, but not for Angular.  This would help to explain how one uses the standard built-in models via Angular.

It should be relatively simple to create a simple example project and generate Angular client and docs using the CLI.  Then we could also add some JSdoc comments, and add the module to the api docs site repos.json.  Might need to do some tweaks because the generated docs are ng-doc style.

**TASKS**
- [x] https://github.com/strongloop-internal/strong-docs/pull/52 Support ngdoc comments
- [x] https://github.com/strongloop/loopback-sdk-angular/pull/91 Enable strong-doc generated API docs for built-in loopback models
- [x]  https://github.com/strongloop-internal/strong-docs/pull/53 Support `{function(param1,param2)}` types. They are rendered as `{function(param1 or param)}` now.
- [x] https://github.com/strongloop-internal/strong-docs/pull/53 Support `{@link href name}` in markdown content.
- [x] add loopback-sdk-angular to apidocs website
